### ISSUE TITLE
Running in local server

### ISSUE THREAD

**Issue by yonkyunior** [juristr/juristr.github.com#4]
Hi, Nice to meet you,
i found out you site using jekyll,
when i wanna run it offline, it gaves me error!

ruby 2.2.3
jekyll 3.0.0

```
E:\02 WEBDEV\03 RESOURCE\001 EXAMPLE\juristr.github.com-master>jekyll serve
Configuration file: E:/02 WEBDEV/03 RESOURCE/001 EXAMPLE/juristr.github.com-mast
er/_config.yml
E:/02 WEBDEV/03 RESOURCE/001 EXAMPLE/juristr.github.com-master/_plugins/debug.rb
:13:in `<module:Jekyll>': cannot load such file -- jekyll/post (LoadError)
        from E:/02 WEBDEV/03 RESOURCE/001 EXAMPLE/juristr.github.com-master/_plu
gins/debug.rb:8:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54
:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54
:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plug
in_manager.rb:75:in `block (2 levels) in require_plugin_files'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plug
in_manager.rb:74:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plug
in_manager.rb:74:in `block in require_plugin_files'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plug
in_manager.rb:73:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plug
in_manager.rb:73:in `require_plugin_files'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/plug
in_manager.rb:18:in `conscientious_require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/site
.rb:97:in `setup'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/site
.rb:49:in `initialize'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/comm
ands/build.rb:30:in `new'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/comm
ands/build.rb:30:in `process'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/comm
ands/serve.rb:26:in `block (2 levels) in init_with_program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `block in execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/program.rb:42:in `go'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y.rb:19:in `program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0/bin/jekyll:17:i
n `<top (required)>'
        from C:/Ruby22-x64/bin/jekyll:23:in `load'
        from C:/Ruby22-x64/bin/jekyll:23:in `<main>'

E:\02 WEBDEV\03 RESOURCE\001 EXAMPLE\juristr.github.com-master>
```

Is there a correct method ~
i read _config.yml
usually, i change the base url or something
i dont know about BASE_PATH : false
to running it very well in local server with jekyll.

Thanks

**Comment by juristr** [comment]
Hi, hmm..very strange. I don't have any special configuration. Simply installed Jekyll following [the docs on the official site](https://jekyllrb.com/) and that's it. Maybe you find something on their site, especially about configuring Windows to run Jekyll properly. Note, I didn't try my blog with the latest Jekyll v3 yet.

Moreover, you could try running it from a path without spaces in it as that might often cause issues. Good luck :smile:

**Comment by yonkyunior** [comment]
Solved! :dancer: 
with running `jekyll _2.4.0_ serve`
jekyll 2.4.0 is the one github supported.
i think you must create a gemfile point to github-pages, to lock this dependencies.

**Comment by juristr** [comment]
Cool :+1:
